### ISSUE TITLE
Feedback DOM manipulation

### ISSUE THREAD

**Issue by remarcmij** [talalalamdar/hyf-javascript1#3]
Hi Talal,

Your web page looks nice. I'm just going to comment on the JavaScript part.

The assignment asked for your `menu` variable to be set up as an **object** rather than an **array**. The object keys should be taken from your `favouriteBooks` array. For example:

```js
let menu = {
  "the-godfather": {
    Title: "The godfather",
    Language: "English",
    Author: "Mario Puzo"
  },
  // etc
}
``` 

I have placed the key `"the-godfather"` within quotes because that contains the `-` character, which is not allowed in a JavaScript identifier. Had you chosen to replace spaces in by an underscore `_` character, then you could leave out the quotes, like this:

```js
let menu = {
  the_godfather: {
    Title: "The godfather",
    Language: "English",
    Author: "Mario Puzo"
  },
  // etc
}
``` 

With this setup, your `favouriteBooks` array defines which books you wish to include in your web page and in what order. Your `menu` object then just becomes a container for the book details.

Your `for` loop needs to be adjusted a bit to make this work:

```js
for (let i = 0; i < favouriteBooks.length; i++) {
	const key = favouriteBooks[i];
	const bookInfo = menu[key];
	// You can now use bookInfo where you used menu[i] previously
}
```

In the `for` loop body, you create an `ul` and two `li` elements. Those `li` elements should be children of the `ul` rather than the containing `div`. You `ul` is empty. I found this out by checking in the Chrome inspector the HTML that was generated by your program.

![talal](https://user-images.githubusercontent.com/2788771/33018009-e9f5347c-cdf4-11e7-9842-380d7e7d28ff.png)

In the code where you add your images and links to the HTML you use hard-coded indexes (0, 1, etc) to access elements in your document. You should try and avoid that. It is better to keep the image and link data in an object and use a `for` loop.

To give you an idea, check out this implementation of the assignment which I adapted from the homework submitted by Nagham.  

https://github.com/remarcmij/class12-js/blob/master/week3/nagham-dom/homework3-2.js

**Comment by talalalamdar** [comment]
@remarcmij Hello Jim, i changed some of my codes as you said in the feedback but my page stopped working for some reason, i think something is wrong with my function, please would you check what is wrong with it ?

**Comment by talalalamdar** [comment]
![screenshot from 2017-11-23 17-47-01](https://user-images.githubusercontent.com/32465000/33183020-80fc0660-d076-11e7-9bed-3be5a0938686.png)
![screenshot from 2017-11-23 17-47-16](https://user-images.githubusercontent.com/32465000/33183021-8129a8a4-d076-11e7-9eb6-df5a6223e914.png)
![screenshot from 2017-11-23 17-47-31](https://user-images.githubusercontent.com/32465000/33183022-8145135a-d076-11e7-9411-37513ae41ab1.png)
![screenshot from 2017-11-23 17-47-43](https://user-images.githubusercontent.com/32465000/33183023-815fa1d4-d076-11e7-9a5a-9c4cb9fddfcb.png)
![screenshot from 2017-11-23 17-47-52](https://user-images.githubusercontent.com/32465000/33183024-81a8d98a-d076-11e7-92fc-a731841151de.png)

**Comment by talalalamdar** [comment]
@remarcmij never mind Jim, i fixed it as you recommended. , thanks :smile:

**Comment by remarcmij** [comment]
Hi Talal, good that you sorted out the problems yourself. There is still something that you can improve. Instead of 'manually' adding the `alt` and `href` attributes with hard-coded indices it more elegant and maintainable if you keep all related info in an object and use your loop to add it to the DOM:

```js
// code omitted

function generator2() {
  for (let i = 0; i < favoriteBooks.length; i++) {
    let div = document.createElement("div");
    let heading = document.createElement("h4");
    let ul = document.createElement("ul");
    let li1 = document.createElement("li");
    let li2 = document.createElement("li");
    let id = document.createAttribute("id");
    const key = favoriteBooks[i];
    const bookInfo = menu[key];
    var keys = Object.keys(bookInfo);
    heading.innerHTML = keys[0] + " : " + bookInfo.Title;
    li1.innerHTML = keys[1] + " : " + bookInfo.Language;
    li2.innerHTML = keys[2] + " : " + bookInfo.Author;
    container.appendChild(div);
    div.appendChild(heading);
    div.appendChild(ul)
    ul.appendChild(li1);
    ul.appendChild(li2);
    id.value = favoriteBooks[i];
    div.setAttributeNode(id);
  }
}
generator2();


//    creating the images and Adding the sources of the images and giving them alt attributes 

let booksCovers = {
  the_godfather: {
    href: "http://gdblogs.shu.ac.uk/b1006221/wp-content/uploads/sites/207/2014/01/book2.jpg",
    alt: "the-godfather-cover",
    link: "https://en.wikipedia.org/wiki/The_Godfather_(novel)"
  },
  the_alchemist: {
    href: "https://images.gr-assets.com/books/1466865451l/492286.jpg",
    alt: "the-alchemist-cover",
    link: "https://en.wikipedia.org/wiki/The_Alchemist_(novel)"
  },
  eleven_minutes: {
    href: "http://www.santjordi-asociados.com/sites/default/files/Eleven%20minutes.jpg",
    alt: "elven-minutes",
    link: "https://en.wikipedia.org/wiki/Eleven_Minutes"
  },
  gone_with_the_wind: {
    href: "https://upload.wikimedia.org/wikipedia/en/6/6b/Gone_with_the_Wind_cover.jpg",
    alt: "gone-with-the-wind-cover",
    link: "https://en.wikipedia.org/wiki/Les_Mis%C3%A9rables"
  },
  les_miserables: {
    href: "https://i.pinimg.com/736x/da/e8/c7/dae8c79909eb122f15e1a38c60970da8--les-mis%C3%A9rables-victor-hugo.jpg",
    alt: "les-miserables-cover",
    link: "https://en.wikipedia.org/wiki/Les_Mis%C3%A9rables"
  },
  the_shining: {
    href: "https://images-na.ssl-images-amazon.com/images/I/81ipXKw8rjL.jpg",
    alt: "the-shining-cover",
    link: "https://en.wikipedia.org/wiki/The_Shining_(novel)"
  },
  a_song_of_ice_and_fire: {
    href: "http://achalaupendran.com/wp-content/uploads/2016/06/song-of-ice-and-fire-book-cover.jpg",
    alt: "a-song-of-ice-and-fire-cover",
    link: "https://en.wikipedia.org/wiki/A_Song_of_Ice_and_Fire"
  },
  harry_potter: {
    href: "http://bookriotcom.c.presscdn.com/wp-content/uploads/2014/08/HP_pb_new_6.jpg",
    alt: "harry-potter-cover",
    link: "https://en.wikipedia.org/wiki/Harry_Potter_and_the_Philosopher%27s_Stone"
  },
  the_girl_with_the_dragon_tattoo: {
    href: "https://images.gr-assets.com/books/1302128966l/2732977.jpg",
    alt: "the-girl-with-the-dragon-tattoo-cover",
    link: "https://en.wikipedia.org/wiki/The_Girl_with_the_Dragon_Tattoo"
  },
  the_fault_in_our_stars: {
    href: "https://images.penguinrandomhouse.com/cover/9780142424179",
    alt: "the-fault-in-our-stars-cover",
    link: "https://en.wikipedia.org/wiki/The_Fault_in_Our_Stars"
  }
}

function addImages() {
  for (let id of Object.keys(booksCovers)) {
    const bookCover = booksCovers[id];
    const div = document.getElementById(id);
    if (div !== null) {
      const link = document.createElement("a");
      link.setAttribute("href", bookCover.link);
      link.innerHTML = "Press me";
      div.appendChild(link);
      const img = document.createElement("img");
      img.setAttribute("src", bookCover.href);
      img.setAttribute("alt", bookCover.alt);
      div.appendChild(img);
    }
  }
}

addImages();
```
